<a href="https://colab.research.google.com/github/kimgeonhee317/d2l-notes/blob/main/notebook/2_1_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.1.1 Getting Started

In [1]:
import torch

In [4]:
# Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based computation
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
# numel() : number of element
x.numel()

12

In [8]:
# shape
x.shape

torch.Size([12])

In [9]:
# reshpae
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
# zeros
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# ones
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# inialize random (The parameters of nn are often initialized randomly)
# randn follow standard Gaussian distributiaon (mean of 0 and st of 1)
torch.randn(3, 4)

tensor([[ 0.3219, -0.4575, -1.2709, -0.4665],
        [ 0.1710,  0.1447, -0.9141,  0.2690],
        [-0.2004,  0.7234,  0.3754, -1.0508]])

## 2.1.2 Indexing and Slicing

In [13]:
# [-1] selects last row, [1:3] select second and third rows
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
# assign value by specifiying indices
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
 # assign multiple elements the same value, ":" in second index means that it takes all element along the column
 X[:2, :] = 12 # 0~1 rows and all cols for that rows
 X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.3 Operations

In [21]:
# unary scalar operators ( f : R -> R)
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [22]:
# binary scalar operators (f : R, R -> R)
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [24]:
# concatenation
# we need to tell the system along which axis to concatenate
# rows for dim=0, cols for dim=1
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.9, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # 3*4 matrix
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 2.9000,  1.0000,  4.0000,  3.0000],
         [ 1.0000,  2.0000,  3.0000,  4.0000],
         [ 4.0000,  3.0000,  2.0000,  1.0000]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.9000,  1.0000,  4.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  1.0000,  2.0000,  3.0000,  4.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000,  2.0000,  1.0000]]))

In [25]:
# logical statements
# X == Y for example
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
# summing all elements
X.sum()

tensor(66.)

## 2.1.4 Broadcasting

Broadcasting works according to the following two-step procedure:
1. Expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape.
2. Perform elementwise operation on resulting arrays

In [28]:
# generate 3*1 matrix a, 1*2 matrix b, both matrices shape are net matche up
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [29]:
# Broadcasting produces a larger 3 * 2 matrix by replicating matrix a along the\
# columns and matrix b along the rows before adding them elemntwise
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])